/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColaboradorCpfRouteImport } from './routes/colaborador.$cpf'

const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorCpfRoute = ColaboradorCpfRouteImport.update({
  id: '/colaborador/$cpf',
  path: '/colaborador/$cpf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/dashboard': typeof DashboardRoute
  '/importar': typeof ImportarRoute
  '/resultados': typeof ResultadosRoute
  '/colaborador/$cpf': typeof ColaboradorCpfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/dashboard': typeof DashboardRoute
  '/importar': typeof ImportarRoute
  '/resultados': typeof ResultadosRoute
  '/colaborador/$cpf': typeof ColaboradorCpfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/dashboard': typeof DashboardRoute
  '/importar': typeof ImportarRoute
  '/resultados': typeof ResultadosRoute
  '/colaborador/$cpf': typeof ColaboradorCpfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colaboradores'
    | '/dashboard'
    | '/importar'
    | '/resultados'
    | '/colaborador/$cpf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/colaboradores'
    | '/dashboard'
    | '/importar'
    | '/resultados'
    | '/colaborador/$cpf'
  id:
    | '__root__'
    | '/'
    | '/colaboradores'
    | '/dashboard'
    | '/importar'
    | '/resultados'
    | '/colaborador/$cpf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  DashboardRoute: typeof DashboardRoute
  ImportarRoute: typeof ImportarRoute
  ResultadosRoute: typeof ResultadosRoute
  ColaboradorCpfRoute: typeof ColaboradorCpfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador/$cpf': {
      id: '/colaborador/$cpf'
      path: '/colaborador/$cpf'
      fullPath: '/colaborador/$cpf'
      preLoaderRoute: typeof ColaboradorCpfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  DashboardRoute: DashboardRoute,
  ImportarRoute: ImportarRoute,
  ResultadosRoute: ResultadosRoute,
  ColaboradorCpfRoute: ColaboradorCpfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
